# Generated by Django 5.1.6 on 2025-06-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundamental',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
