# Generated by Django 5.2 on 2025-04-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('buy', '매수'), ('sell', '매도')], max_length=10)),
                ('order_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
